# Generated by Django 5.0 on 2024-03-17 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='Department', to='Group.group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(null=True, related_name='group', to=settings.AUTH_USER_MODEL),
        ),
    ]
