# Generated by Django 5.0 on 2024-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_alter_group_members_departmentmanager_groupleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='Department', to='Group.group'),
        ),
    ]
