# Generated by Django 5.0 on 2023-12-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0002_alter_report_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
