# Generated by Django 5.0 on 2024-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Report', '0003_alter_report_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.JSONField(),
        ),
    ]
